name: parties
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  floating_action_bubble: ^1.1.4
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_swiper_null_safety: ^1.0.2
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  liquid_swipe: ^3.1.0
  loading_animation_widget: ^1.2.1
  path: ^1.8.3
  photo_view: ^0.14.0
  provider: ^6.1.2
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Bold.ttf
          weight: 900
        - asset: assets/fonts/Mada-Medium.ttf
          weight: 300
        - asset: assets/fonts/Mada-Regular.ttf

  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
